#!/bin/bash
# Test vanilla LiteLLM vs your custom version

echo "=========================================="
echo "Testing Vanilla LiteLLM"
echo "=========================================="
echo ""
echo "Step 1: Create test config with vanilla LiteLLM"
echo "Step 2: Test with Cursor-style requests"
echo ""
echo "To test:"
echo "1. Create a new branch from upstream main"
echo "2. Start proxy with vanilla code"
echo "3. Try using it with Cursor"
echo "4. See if you hit the same bugs you fixed"
echo ""
echo "Commands to test:"
echo ""
echo "# Checkout vanilla LiteLLM (no your fixes)"
echo "git stash"
echo "git checkout 5d456bcdc3  # Commit before your fixes"
echo ""
echo "# Start vanilla proxy"
echo "docker-compose -f docker-compose.vertex-claude.yml down"
echo "docker build -t litellm-vanilla ."
echo "# Update docker-compose to use litellm-vanilla"
echo ""
echo "# Test with Cursor"
echo "# Try using tools/functions"
echo "# Try thinking mode"
echo "# See if you get errors"
echo ""
echo "If vanilla works = You can remove your fixes ✅"
echo "If vanilla breaks = Your fixes are necessary ❌"
